SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE DATABASE university_hibernate WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';

ALTER DATABASE university_hibernate OWNER TO postgres;

\connect university_hibernate

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA main;

ALTER SCHEMA main OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE main.courses (
    id bigint NOT NULL,
    title character varying(255)
);

ALTER TABLE main.courses OWNER TO postgres;

ALTER TABLE main.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE main.groups (
    id bigint NOT NULL,
    number character varying(255)
);


ALTER TABLE main.groups OWNER TO postgres;

ALTER TABLE main.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE main.students (
    id bigint NOT NULL,
    age integer NOT NULL,
    name character varying(255),
    olympicgamer boolean NOT NULL,
    score double precision NOT NULL,
    group_id bigint
);


ALTER TABLE main.students OWNER TO postgres;

CREATE TABLE main.students_courses (
    students_id bigint NOT NULL,
    courses_id bigint NOT NULL
);


ALTER TABLE main.students_courses OWNER TO postgres;

ALTER TABLE main.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY main.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY main.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


ALTER TABLE ONLY main.students_courses
    ADD CONSTRAINT students_courses_pkey PRIMARY KEY (students_id, courses_id);

ALTER TABLE ONLY main.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

ALTER TABLE ONLY main.students_courses
    ADD CONSTRAINT fk9pvsjc57msc71fdgr6fu6as5w FOREIGN KEY (courses_id) REFERENCES main.courses(id);

ALTER TABLE ONLY main.students
    ADD CONSTRAINT fkmsev1nou0j86spuk5jrv19mss FOREIGN KEY (group_id) REFERENCES main.groups(id);

ALTER TABLE ONLY main.students_courses
    ADD CONSTRAINT fkoujw2aln3p6ntrwqahliskhfm FOREIGN KEY (students_id) REFERENCES main.students(id);